### PR TITLE
Ledger Interval API

### PR DESCRIPTION
**Pull request by juliusfrost**
Adds an initial implementation of the Plutus.V1.Ledger.Interval in eopsin

### CODE REVIEW

**Comment by juliusfrost** [comment]
@nielstron I'm not sure what's the best way to add this to the prelude.

**Comment by nielstron** [comment]
Yeah I'm not sure either. The names are pretty generic so I would prefer not importing them by default. we can also simply not import in the prelude by default until we have a fancy import + renaming system

**Comment by nielstron** [comment]
The ledger API (also the parts in the prelude) could actually be re-used by hebi and pycardano. Might make sense to make it a seperate package in the long term?

For now we can just put it in Eopsin.ledger and everyone who needs it just imports it

**Comment by juliusfrost** [comment]
@nielstron This should be ready to merge. Thanks!

**Pull request merged**
